# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c3e88701100ece69dfae97ee414daae468e38b82e8f453c94a3b5482988bafc6a14b2600e652f2fbfa65c01d2c511883ec0054eb4023b17ad6f750b169c6af

test:
  secret_key_base: 604ea7bc9f1c980c1f19978b7244dbce4426c98311997b79291bc0630dfa4ebd0d12414e71d2e517cf87657f5504102bf8817115de67efe093c67de29121f1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
